##############################
# ETL settings for worker
##############################

name: TemplateWorker

##############################
# Scheduler
##############################
schedule: False
interval:
  seconds: 5

##############################
# Pipelines
##############################
pipelines:
  - file:
    - urls:
      - length:
        - stdout
      - reverse:
        - length:
          - stdout

##############################
# Plugins
##############################

# Arguments to be passed to plugins on initialization
plugin_kwargs:
  file:
    paths:
      - /home/ubuntu/urls
    splitLines: true
    
# Plugin directories are places to look for plugins that inherit the
# base.  Directory paths can be absolute or relative
plugin_directories:
  - plugins
  - ../../plugins

# You can also specify the absolute path to each plugin manually
plugin_paths:
  example: /home/ubuntu/example.py