signpost:
  url: http://172.16.128.94
  user: None
  password: None
  port: 80

tcga_dcc:
  latest_url: http://tcga-data.nci.nih.gov/datareports/resources/latestarchive
  latest_firstline: 'ARCHIVE_NAME	DATE_ADDED	ARCHIVE_URL'
  open_url: https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/anonymous/tumor/
  protected_url: https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/tcga4yeo/tumor/

logging:
  level: INFO
  format: '%(asctime)s %(name)-6s %(levelname)-4s %(message)s' 
  log_dir: '/var/log/tungsten'