signpost:
  url: http://172.16.128.94
  user: None
  password: None
  port: 80

logging:
  level: DEBUG
  format: '%(asctime)s %(name)-6s %(levelname)-4s %(message)s' 
  log_dir: '/var/log/tungsten'

download:
  id: 'cghub_data_downloader_0'
  key: '/home/ubuntu/aheath_cghub.key'
  dir: '/mnt/cinder/download'