signpost:
  url: http://172.16.128.94
  user: None
  password: None
  port: 80

cghub:
  url: 'https://cghub.ucsc.edu/cghub/metadata/analysisDetail?'
  query_str: 'library_strategy=RNA-Seq'
#  query_str: 'analysis_id=34c9ff85-c2f8-45dc-b4aa-fba05748e355'

logging:
  level: DEBUG
  format: '%(asctime)s %(name)-6s %(levelname)-4s %(message)s' 
  log_dir: '/var/log/tungsten'