##############################
# Center code insertion
##############################

name: center_codes
log_level: INFO

plugins:
  - uri:
    - tsv2graph:
      - graph2neo
        
plugin_kwargs:
  uri:
    docs:
      - /home/ubuntu/zugs/data_model/tables/centerCodes.tsv
  
  tsv2graph:
    type: center
    id_field: Code
      
  graph2neo:
    host: 172.16.128.74
    port: 7474

plugin_directories:
  - /home/ubuntu/zugs/data_model/plugins
    