##############################
# ETL settings for worker
##############################

name: CGHubImport
log_level: INFO

##############################
# Scheduler
##############################
schedule: False
interval:
  seconds: 5

##############################
# Pipelines
##############################
plugins:
  - download_consumer
  
##############################
# Plugins
##############################

processors:
  download_consumer: 10

##### Arguments to be passed to plugins on initialization
plugin_kwargs:

  download_consumer:
    host: localhost
    port: 7474
    max_retries: 2

##### You can specify plugin class names, the default is the module name    
# plugin_class_names:
#   latest_urls: latest_urls
    
##### Plugin directories are places to look for plugins that inherit the
##### base.  Directory paths can be absolute or relative
# plugin_directories:
#   - plugins

##### You can also specify the absolute path to each plugin manually
plugin_paths:
  example: /home/ubuntu/example.py
  