##############################
# ETL settings for worker
##############################

name: ExampleZug
log_level: INFO

##############################
# Scheduler
##############################
schedule: False
interval:
  seconds: 5

##############################
# Pipelines
##############################
plugins:
  - uri:
    - xml2graph:
      - graph2neo

  - latest_urls:
    - extract_tar:
      - xml2graph:
        - graph2neo
        
##############################
# Plugins
##############################

processors:
  extract_tar: 2
  xml2graph: 2
  graph2neo: 1

##### Arguments to be passed to plugins on initialization
plugin_kwargs:

  uri:
    docs:
      - /home/ubuntu/nationwidechildrens.org_biospecimen.TCGA-AR-A1AR.xml

  extract_tar:
    regex: ".*(bio).*(Level_1).*\\.xml"
      
  latest_urls:
    latest_firstline: 'ARCHIVE_NAME	DATE_ADDED	ARCHIVE_URL'
    latest_url: http://tcga-data.nci.nih.gov/datareports/resources/latestarchive
    open_url: https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/anonymous/tumor/
    protected_url: https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/tcga4yeo/tumor/

    constraints:
      data_level: Level_1
      platform: bio

    url_key: dcc_archive_url
    
  xml2graph:
    translate_path: /home/ubuntu/workers/data_model/translate.yml
    data_type: biospecimen

  graph2neo:
    host: localhost
    port: 7474
    max_retries: 0

##### You can specify plugin class names, the default is the module name    
# plugin_class_names:
#   latest_urls: latest_urls
    
##### Plugin directories are places to look for plugins that inherit the
##### base.  Directory paths can be absolute or relative
# plugin_directories:
#   - plugins

##### You can also specify the absolute path to each plugin manually
plugin_paths:
  example: /home/ubuntu/example.py
  