##############################
# ETL settings for worker
##############################

name: TemplateWorker

##############################
# Scheduler
##############################
schedule: False
interval:
  seconds: 5

##############################
# Pipelines
##############################
pipelines: 
  - latest_urls:
    - extract_xml:
      - xml2bcr:
        - bcr2neo
        - count

##############################
# Plugins
##############################

# Arguments to be passed to plugins on initialization
plugin_kwargs:
  file:
    splitLines: false
    paths:
      - /home/ubuntu/nationwidechildrens.org_biospecimen.TCGA-AR-A1AR.xml

  latest_urls:
    latest_firstline: 'ARCHIVE_NAME	DATE_ADDED	ARCHIVE_URL'
    latest_url: http://tcga-data.nci.nih.gov/datareports/resources/latestarchive
    open_url: https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/anonymous/tumor/
    protected_url: https://tcga-data.nci.nih.gov/tcgafiles/ftp_auth/distro_ftpusers/tcga4yeo/tumor/
    
  xml2bcr:
    translate_path: /home/ubuntu/workers/data_model/translate.yml
    data_type: biospecimen

  bcr2neo:
    host: localhost
    port: 7474
    
  stdout:
    pprint: False
    
# Plugin directories are places to look for plugins that inherit the
# base.  Directory paths can be absolute or relative
plugin_directories:
  - plugins
  - ../../plugins

# You can also specify the absolute path to each plugin manually
plugin_paths:
  example: /home/ubuntu/example.py