##############################
# ETL settings for worker
##############################

name: CGHubDowload
log_level: INFO


##############################
# Plugins
##############################

plugins:
  - claim_work:
    - downloader:
      - checksum:
        - upload2swift:
          - post2signpost:
            - finish_work
  
##############################
# Plugins
##############################

processors:
  download_consumer: 1

##### Arguments to be passed to plugins on initialization
plugin_kwargs:

  claim_work:
    host: neo4j

  post2signpost:
    host: signpost

  downloader:
    cghub_key: /etc/tungsten/authorization/cghub/download_key
    download_path: /mnt/cinder/scratch/