
# Plugins
plugins:

  paths:
    schedulers: plugins/schedulers
    conversions: plugins/conversions
    exports: plugins/exports

  schedulers:
    - file
  
  conversions:
    - json_flat

  exports:
    - postgres
    - couchdb
    - stdout

postgres:
  database: dcc_datamodel
  user: postgres
  password: password
  host: localhost
  port: 5432

json_flat:
  flatten: True

file:
  path: /home/ubuntu/xml_list