
# Plugins
plugins:

  paths:
    schedulers: plugins/schedulers
    conversions: plugins/conversions
    exports: plugins/exports

  schedulers:
    - file
  
  conversions:
    - json_flat

  exports:
    - postgres
    # - stdout


postgres:
  database: dcc_datamodel
  user: postgres
  password: password
  host: localhost
  port: 5432
  table: dcc_datamodel
  onlyConversions:
    - json_flat

json_flat:
  flatten: True

file:
  path: /home/ubuntu/xml_list

# Below is an example of how to tell a plugin to ignore a scheduler or
# conversion plugin that passed it a document

stdout:
  ignoreConversions: 
    - json_nested

  ignoreSchedulers: 
    - signpost