signpost:
  url: http://172.16.128.94
  user: None
  password: None
  port: 80

# Signpost document containing state of worker.
#state: 07e28aec-ba31-409d-821f-18aac205f4a8
state: 0d65af0e-a457-48d9-989d-6eec83a4f995

# Input document query.
query: '{"_type":"cghub_import","import":{"state":"complete"}}'

logging:
  level: DEBUG
  format: '%(asctime)s %(name)-6s %(levelname)-4s %(message)s' 
  log_dir: '/var/log/tungsten'
